module:

  _target_: models.classifier_model.ClassifierModel

  dropout: 0.3

  speaker_a : 1.0
  label_a: 2.5

  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-5
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0.02

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    patience: 3

  # lr_scheduler:
  #   _target_: torch.optim.lr_scheduler.CosineAnnealingLRScheduler
  #   T_max: 5
    
  monitor: ${train.monitor.metric}
  mode: ${train.monitor.mode}

  process_audio_method: ${datamodule.datamodule.process_audio_method}
  spectrogram_method: ${datamodule.datamodule.spectrogram_method}
  checkpoint: 'artifacts/model-30249sth:v0/model.ckpt'