module:

  _target_: models.classifier_model.ClassifierModel

  dropout: 0.3

  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-5
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0.02

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    patience: 3
    
  monitor: ${train.monitor.metric}
  mode: ${train.monitor.mode}

  process_audio_method: ${datamodule.datamodule.process_audio_method}
  spectrogram_method: ${datamodule.datamodule.spectrogram_method}
  checkpoint: '/home/konradkaranowski/Speech-And-Speaker-Detection/logs/Speech_And_Speaker_Detection/1zn9x2ub/checkpoints/epoch=11-step=19415.ckpt'