module:

  _target_: models.siamese_model.SiameseModel

  final_dim_rep: 256

  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-4
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0.02

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    patience: 3
    
  monitor: ${train.monitor.metric}
  mode: ${train.monitor.mode}


  backbone:
    _target_: models.backbones.cataluna.CatalunaBackbone

  process_audio_method: ${datamodule.datamodule.process_audio_method}
  spectrogram_method: ${datamodule.datamodule.spectrogram_method}