datamodule:

  _target_: datamodules.datamodule.SpeechDataModule

  process_audio_method:
    _target_: utils.spectrogram_utils.preprocess_signal
      # params
    target_sr: 22050
    target_num_samples: 22050
    res_type: 'kaiser_best'

  spectrogram_method:
    _target_: utils.spectrogram_utils.create_mel_spectrogram
    #_target_: utils.spectrogram_utils.create_mfcc_spectrogram
    # params
    frame_size: 2048 
    hop_size: 128
    window_function: 'hann'
    num_mels: 128
    num_mfccs: 39

  # data paths
  root: 'C:/Users/Konrad/Desktop/PythonProjects/Speech-And-Speaker-Detection/data'#'/home/konradkaranowski/storage'
  data_dir: 'archive' #'speech'
  img_dir: 'mel_spectrogram' #'mfcc_spectrograms_22050'

  # datasets specs
  train_vs_rest_size: 0.8
  val_vs_test_size: 0.4
  batch_size: 5