datamodule:

  _target_: datamodules.datamodule.SpeechDataModule

  # process signal
  target_sr: 22050
  target_num_samples: 22050 
  res_type: 'kaiser_best'

  spectrogram_method:
    # _target_: utils.spectrogram_utils.create_mel_spectrogram
    _target_: utils.spectrogram_utils.create_mfcc_spectrogram
    # create spectrogram
    frame_size: 2048 
    hop_size: 128
    window_function: 'hann'
    num_mels: 128
    num_mfccs: 39

  # data paths
  root: '/home/konradkaranowski/storage'
  data_dir: 'speech'
  img_dir: 'mfcc_spectrograms_22050'

  # datasets specs
  train_vs_rest_size: 0.8
  val_vs_test_size: 0.4
  batch_size: 24