# metadata specialised for each experiment
core:
  project_name: 'Speech_And_Speaker_Detection'
  storage_dir: ${oc.env:PROJECT_ROOT}/logs
  version: 0.0.1
  tags: null

defaults:
  - hydra: default
  - model: fine_tune
  - datamodule: fine_tune
  - train: fine_tune
  - _self_
  # - _self_ 
#  - hydra/launcher: joblib