# deterministic


trainer:
  gpus: -1
  max_epochs: 100
  min_epochs: 0

datamodule:
  data_url: ''
  train_vs_rest_size: 0.8
  val_vs_test_size: 0.3

  # process signal
  target_sr: 22050
  taregt_num_samples: 22050
  res_type: 'kaiser_best'

  # spectrogram
  frame_size: 2048
  hop_size: 128
  window_function: 'hann'

